name: Test and Validate Bash Scripts

on:
  pull_request: # Run on pull requests to the main branch
    branches:
      - main
    paths:
      - 'main/testing/test.sh' # Trigger only for changes to the specific file
  push: # Optional: Run on push to the main branch
    branches:
      - main
    paths:
      - 'main/testing/test.sh' # Trigger only for changes to the specific file

jobs:
  test-scripts:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Install dependencies needed for the scripts
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y curl tar jq bc lsb-release build-essential shellcheck shfmt

    # Run ShellCheck for linting
    - name: Lint Shell Scripts with ShellCheck
      run: |
        shellcheck main/testing/test.sh

    # Run shfmt for formatting validation
    - name: Format Shell Scripts with shfmt
      run: |
        shfmt -d main/testing/test.sh

    # Test the specific script (test.sh)
    - name: Run test.sh
      run: |
        chmod +x main/testing/test.sh
        main/testing/test.sh

    # Validate that the script completed successfully
    - name: Validate Script
      run: echo "Script passed successfully!"
